name: Update Congo News

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create a test file
        run: echo "This is a test" > test.txt
      
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'test.txt'
          message: 'Add test file'
          default_author: github_actions
